fn main() {
    // Tauri's `externalBin` convention resolves each declared sidecar to a file
    // suffixed with the Rust *target triple* (see the comment block in
    // src/sidecar.rs). Cargo knows that triple here and nowhere else at
    // runtime, so hand it to the crate as a compile-time env var. This keeps
    // one source of truth for the filename shared by the bundler, the runtime
    // lookup, and sidecar_build/build_sidecar.py.
    println!(
        "cargo:rustc-env=SOPKB_TARGET_TRIPLE={}",
        std::env::var("TARGET").expect("cargo always sets TARGET for build scripts")
    );

    // Declaring the app's own commands here autogenerates the
    // `allow-<kebab-case-command>` ACL permissions under
    // src-tauri/permissions/autogenerated/, which capabilities/default.json then
    // references. Required, not optional boilerplate: without a matching
    // permission grant, an IPC call fails at runtime with "<command> not allowed".
    //
    // Keep this list in sync with `src/main.rs`'s `tauri::generate_handler!` list --
    // one entry per Tauri command, PORT_PLAN.md §4's full surface.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
        // §4.1
        "get_workbench_context",
        "resolve_launch_target",
        "set_workbench_root",
        "pick_workbench_folder",
        "select_bundle",
        "deselect_bundle",
        // §4.2
        "list_bundles",
        "create_project",
        "describe_bundle",
        "init_bundle",
        "repair_bundle_dirs",
        "get_legacy_state_status",
        // §4.3
        "pick_source_files",
        "pick_source_folder",
        "stage_source_files",
        "get_staged_sources",
        "clear_staged_sources",
        "run_ingest_pipeline",
        "preview_ingest_pipeline",
        "scan_sources",
        "normalize_sources",
        "mine_knowledge",
        "validate_bundle",
        // §4.4
        "list_sources",
        "get_source",
        "get_normalized_text",
        "get_source_stats",
        "list_sections",
        "get_section",
        "list_knowledge_items",
        "get_knowledge_item",
        "search_knowledge",
        "get_evidence",
        "resolve_citation",
        "get_concept_index",
        "get_concept_detail",
        "get_review_detail",
        "get_graph",
        "get_reports",
        "get_validation_summary",
        "get_conflicts_report",
        "get_freshness_report",
        "get_agent_guide",
        "list_authored_drafts",
        "get_authored_draft",
        // §4.5
        "approve_item",
        "reject_item",
        "defer_item",
        "comment_item",
        "edit_item",
        "list_review_events",
        // §4.6
        "list_agent_tasks",
        "get_agent_transcript",
        "run_agent_chat",
        "get_task_context",
        "get_scenario_context",
        "clear_agent_transcript",
        // §4.7
        "export_bundle",
        "sync_okf_documents",
        "get_export_dir",
        "reveal_path",
        // §4.8
        "get_settings",
        "save_profile",
        "delete_profile",
        "set_default_profile",
        "set_reviewer_name",
        "test_profile_connection",
        // §4.9
        "search_relations",
        "get_relation_neighborhood",
        // §4.10
        "get_mcp_invocation",
    ])))
    .expect("failed to run tauri-build");
}
